Update Setup

diff --git a/.github/workflows/xcframework.yml b/.github/workflows/xcframework.yml
--- a/.github/workflows/xcframework.yml
+++ b/.github/workflows/xcframework.yml
@@ -91,13 +91,16 @@ jobs:
           # Convert JSON array to space-separated string
           SDK_LIST="${{ inputs.sdk }}"
           SDK_LIST="${SDK_LIST//[\[\]\",]/}" # Remove JSON characters [, ], ", and spaces
+          echo "Parsed SDK list: $SDK_LIST"
           
           IFS=' ' read -r -a SDKS <<< "$SDK_LIST"
           FRAMEWORKS_ARGS=()
           for SDK in "${SDKS[@]}"; do
               ARCHIVE_PATH="./.build/${{ inputs.xcFrameworkName }}-${SDK}.xcarchive/Products/Library/Frameworks/${{ inputs.xcFrameworkName }}.framework"
+              echo "Checking archive path: $ARCHIVE_PATH"
               if [ -d "$ARCHIVE_PATH" ]; then
                   FRAMEWORKS_ARGS+=("-framework $ARCHIVE_PATH")
+                  echo "Archive path valid: $ARCHIVE_PATH"
               else
                   echo "Warning: Archive path for SDK $SDK does not exist: $ARCHIVE_PATH"
               fi
@@ -107,8 +110,11 @@ jobs:
               exit 1
           fi
           
+          # Debugging: Output the final command before execution
+          echo "Executing xcodebuild with args: ${FRAMEWORKS_ARGS[@]}"
+          
           # Create XCFramework using the accumulated framework arguments
-          xcodebuild -create-xcframework "${FRAMEWORKS_ARGS[@]}" -output ${{ inputs.xcFrameworkName }}.xcframework
+          xcodebuild -create-xcframework "${FRAMEWORKS_ARGS[@]}" -output ${{ inputs.xcFrameworkName }}.xcframework || { echo "xcodebuild failed"; exit 1; }
           
           rm -rf .build
     # - name: Commit and push XCFramework
