Update Setup

diff --git a/.github/workflows/xcframework.yml b/.github/workflows/xcframework.yml
--- a/.github/workflows/xcframework.yml
+++ b/.github/workflows/xcframework.yml
@@ -15,8 +15,8 @@ on:
         description: 'The path of the Xcode Workspace file (including the file extension).'
         type: string
         required: true
-      xcFrameworkName:
-        description: 'The name of the to be created XCFramework. It must not include the default XCFramework extension ".xcframework" as the file naming is automatically done be the workflow.'
+      xcFrameworkNames:
+        description: 'A JSON-based collection of framework names to be built and included in the XCFramework.'
         type: string
         required: true
       scheme:
@@ -62,23 +62,29 @@ on:
         description: 'GitHub Personal Access Token (PAT) if the to-be-commited-to branch is protected and needs a specific access token to push commits to the branch'
         required: false
   
-
+ 
 jobs:
-  build-xcarchive:
-    name: Build XCArchive
+  build-xcarchives: 
+    name: Build XCArchives
+    strategy:
+      matrix:
+        framework: ${{ fromJson(inputs.frameworkNames) }}
     uses: StanfordBDHG/.github/.github/workflows/archive.yml@v2
     with:
       workspaceFile: ${{ inputs.workspaceFile }}
-      xcArchiveName: ${{ inputs.xcFrameworkName }}
+      xcArchiveName: ${{ matrix.framework }}
       scheme: ${{ inputs.scheme }}
       version: ${{ inputs.version }}
       configuration: ${{ inputs.configuration }}
       runsonlabels: ${{ inputs.runsonlabels }}
       sdk: ${{ inputs.sdk }}
-  create-xcframework-and-release:
-    name: Build XCFramework
+  build-xcframeworks:
+    name: Build XCFrameworks
     runs-on: ${{ fromJson(inputs.runsonlabels) }}
-    needs: build-xcarchive
+    needs: build-xcarchives
+    strategy:
+      matrix:
+        framework: ${{ fromJson(inputs.frameworkNames) }}
     steps:
     - uses: actions/checkout@v4
       with:
@@ -97,7 +103,7 @@ jobs:
         merge-multiple: true
     - name: Unpack XCArchives and create XCFramework
       run: |
-          rm -rf ${{ inputs.xcFrameworkName }}.xcframework
+          rm -rf ${{ matrix.framework }}.xcframework
           
           # Convert JSON array to space-separated string
           SDK_LIST="${{ inputs.sdk }}"
@@ -108,9 +114,9 @@ jobs:
           FRAMEWORKS_ARGS=""
           for SDK in "${SDKS[@]}"; do
               # Unpack the XCArchive
-              tar -zxvf ./.build/${{ inputs.xcFrameworkName }}-${SDK}.xcarchive.tar.gz -C ./.build/
+              tar -zxvf ./.build/${{ matrix.framework }}-${SDK}.xcarchive.tar.gz -C ./.build/
               # Specify the path to the framework within the XCArchive
-              ARCHIVE_PATH="./.build/${{ inputs.xcFrameworkName }}-${SDK}.xcarchive/Products/Library/Frameworks/${{ inputs.xcFrameworkName }}.framework"
+              ARCHIVE_PATH="./.build/${{ matrix.framework }}-${SDK}.xcarchive/Products/Library/Frameworks/${{ matrix.framework }}.framework"
               echo "Checking archive path: $ARCHIVE_PATH"
               if [ -d "$ARCHIVE_PATH" ]; then
                   FRAMEWORKS_ARGS+="-framework $ARCHIVE_PATH "
@@ -124,28 +130,38 @@ jobs:
           FRAMEWORKS_ARGS=$(echo "$FRAMEWORKS_ARGS" | xargs)
           
           echo "Executing xcodebuild with args: $FRAMEWORKS_ARGS"
-          xcodebuild -create-xcframework $FRAMEWORKS_ARGS -output ${{ inputs.outputpath }}/${{ inputs.xcFrameworkName }}.xcframework | xcbeautify || { echo "xcodebuild failed"; exit 1; }
+          xcodebuild -create-xcframework $FRAMEWORKS_ARGS -output ${{ matrix.framework }}.xcframework | xcbeautify || { echo "xcodebuild failed"; exit 1; }
           
           rm -rf .build
-    - name: Commit and push XCFramework
-      uses: EndBug/add-and-commit@v9
-      if: ${{ !inputs.dryRun }}
+    - name: Upload Artifact
+      uses: actions/upload-artifact@v4
       with:
-        add: ${{ inputs.xcFrameworkName }}.xcframework
-        message: Create XCFramework for release ${{ inputs.version }}
+        name: ${{ matrix.framework }}.xcframework
+        path: ${{ matrix.framework }}.xcframework
+
+  commit-and-release:
+    name: Commit and Release XCFrameworks
+    runs-on: ${{ fromJson(inputs.runsonlabels) }}
+    needs: build-xcframeworks
+    steps:
+    - uses: actions/checkout@v4
+      with:
+        token: ${{ secrets.access-token || github.token }}
+    - name: Download Artifacts
+      uses: actions/download-artifact@v4
+      with:
+        path: ./
+        merge-multiple: true
+    - name: Commit and push XCFrameworks
+      uses: EndBug/add-and-commit@v9
+      with:
+        add: "*.xcframework"
+        message: Create XCFrameworks for release ${{ inputs.version }}
         tag: '${{ inputs.version }} --force'
         tag_push: '--force'
         github_token: ${{ secrets.access-token || github.token }}
         author_name: ${{ inputs.user || github.actor }}
         author_email: ${{ inputs.user || github.actor }}@users.noreply.github.com
-    - name: Create Artifacts
-      run: |
-          tar -zcvf ${{ inputs.xcFrameworkName }}.xcframework.tar.gz ${{ inputs.xcFrameworkName }}.xcframework
-    - name: Upload Artifact
-      uses: actions/upload-artifact@v4
-      with:
-        name: ${{ inputs.xcFrameworkName }}.xcframework.tar.gz
-        path: ${{ inputs.xcFrameworkName }}.xcframework.tar.gz
     - name: Create Release
       uses: softprops/action-gh-release@v1
       if: ${{ !inputs.dryRun }}
@@ -153,4 +169,5 @@ jobs:
         tag_name: ${{ inputs.version }}
         generate_release_notes: true
         fail_on_unmatched_files: true
-        files: ${{ inputs.xcFrameworkName }}.xcframework.tar.gz
+        files: |
+          *.xcframework
